# Configurazione principale del sito
site_name: "Francesco Mignogna - MDEF & Fab Lab Barcelona"
site_description: "Master in Design for Emergent Futures"
site_author: "Student Name"
copyright: "Copyleft 2023 Student Name - GNU Free Documentation License"
repo_name: "Name : Github Repo"
site_url: "https://fablabbcn.github.io/mdef-template/"
repo_url: "https://github.com/fablabbcn/mdef-template"

# Navigazione
nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
  - Term 1:
      - Term 1:
          - Design studio 0: term1/01-Design studio 0.md
          - AoWS: term1/02-Atlas of Weak Signals.md
  
          - digi: term1/01-Bootcamp.md
          - studio: term1/01-Bootcamp.md
          
# Extra
extra:
  homepage: "https://mig-sketch.github.io/lavezzi-mdef/"
  social:
    - icon: fontawesome/brands/medium
      link: "https://medium.com/"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

# Tema
theme:
  name: material
  logo: "assets/docs/images/images.jpg"
  favicon: "images/favicon.svg"
  palette:
    - scheme: slate
      primary: "blue-grey"   # qui cambiato da lime a blue-grey
      accent: "lime"         # puoi cambiare in base ai dettagli luminosi che vuoi
  font:
    text: "Be Vietnam"
    code: "Cutive Mono"
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

# Plugin
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

# Estensioni Markdown
markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs"
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

# CSS extra
extra_css:
  - "stylesheets/extra.css"
  - "https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"
