# ===============================
# CONFIGURAZIONE PRINCIPALE DEL SITO
# ===============================
site_name: "Francesco Mignogna - MDEF & Fab Lab Barcelona"
site_description: "Master in Design for Emergent Futures"
site_author: "Student Name"
copyright: "Copyleft 2023 Student Name - GNU Free Documentation License"
repo_name: "Name : Github Repo"
site_url: "https://fablabbcn.github.io/mdef-template/"
repo_url: "https://github.com/fablabbcn/mdef-template"

# ===============================
# NAVIGAZIONE
# ===============================
nav:
  - Home: index.md
  - About: about/me.md
  - Term 1:
      - Design studio 01: term1/01-Design studio 01.md
      - Narratives - Digital Gardening: term1/Narratives - Digital Gardening.md
      - Fundamental for Future Makers: term1/Fundamental for Future Makers.md
      - Reflections 1 - Living with your own ideas: term1/Reflections 1 - Living with your own ideas.md

  - Term 2:
      - Design studio: term2/per i posteri.md
      

# ===============================
# EXTRA
# ===============================
extra:
  homepage: "https://mig-sketch.github.io/lavezzi-mdef/"
  social:
    - icon: fontawesome/brands/medium
      link: "https://medium.com/"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

# ===============================
# TEMA
# ===============================
theme:
  name: material
  logo: "assets/docs/images/images.jpg"
  favicon: "images/favicon.svg"
  palette:
    - scheme: slate
      primary: "blue-grey"   # colore principale
      accent: "lime"         # colore di accento
  font:
    text: "Be Vietnam"
    code: "Cutive Mono"
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

# ===============================
# PLUGIN
# ===============================
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

# ===============================
# ESTENSIONI MARKDOWN
# ===============================
markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs"
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

# ===============================
# CSS EXTRA
# ===============================
extra_css:
  - "stylesheets/extra.css"
  - "https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"

